{ config, pkgs, ... }:

{
  # This value determines the NixOS release with which your system is to be compatible
  system.stateVersion = "$distrib_codename";

  boot = {
    initrd = {
      luks = {
        reusePassphrases = true;
        devices = { 
          luks-root = { 
            device = ""; 
            allowDiscards = true;
            fallbackToPassword = true;
          };
        };
      };
      network = {
        # use udhcp to get an ip address.
        enable = true;
        ssh = {
          enable = true;
          # because a different host key is used, port could be changed
          port = 22; 
          # dropbear uses key format different from openssh; can be generated by using:
          # $ nix-shell -p dropbear --command "dropbearkey -t ecdsa -f /tmp/initrd-ssh-key"
          hostECDSAKey = /run/keys/initrd-ssh-key;
          # public ssh key used for login
          authorizedKeys = [ "$authorized_keys_data" ];
        };
      };
    };
    loader = {
      # Use GRUB 2
      grub = {
        enable = true;
        version = 2;
        efiSupport = true;
        efiInstallAsRemovable = true;
        zfsSupport = true;
      };
    };
  };

  networking = {
    hostName = "$hostname"; # Define your hostname.
    # ZFS (and maybe others) require the networking.hostId option
    hostId = "$hostid";
    # The global useDHCP flag is deprecated, therefore explicitly set to false here.
    # Per-interface useDHCP will be mandatory in the future, so this generated config
    # replicates the default behaviour.
    useDHCP = false;
    interfaces.enp0s2.useDHCP = true;
    # wireless.enable = true;  # Enables wireless support via wpa_supplicant.
    
    # Configure network proxy if necessary
    # proxy.default = "http://user:password@proxy:port/";
    # proxy.noProxy = "127.0.0.1,localhost,internal.domain";
  };
  
  # Enable the OpenSSH daemon.
  services = {
    openssh.enable = true;
  };
  
}

